\timing

--
-- create a SRC table for chicago_business_licenses and
--   load the initial source file
--
DROP TABLE IF EXISTS SRC_chicago_business_licenses;

CREATE TABLE IF NOT EXISTS SRC_chicago_business_licenses(
ID VARCHAR(16),
LICENSE_ID INTEGER,
ACCOUNT_NUMBER INTEGER,
SITE_NUMBER INTEGER,
LEGAL_NAME VARCHAR(150),
DOING_BUSINESS_AS_NAME VARCHAR(150),
ADDRESS VARCHAR(80),
CITY VARCHAR(30),
STATE CHAR(2),
ZIP_CODE CHAR(5),
WARD INTEGER,
PRECINCT INTEGER,
POLICE_DISTRICT INTEGER,
LICENSE_CODE INTEGER,
LICENSE_DESCRIPTION VARCHAR(100),
LICENSE_NUMBER INTEGER,
APPLICATION_TYPE VARCHAR(50),
PAYMENT_DATE DATE,
LICENSE_TERM_START_DATE DATE,
LICENSE_TERM_EXPIRATION_DATE DATE,
DATE_ISSUED DATE,
LICENSE_STATUS VARCHAR(10),
LICENSE_STATUS_CHANGE_DATE DATE,
LATITUDE FLOAT8,
LONGITUDE FLOAT8,
LOCATION POINT,
PRIMARY KEY(LICENSE_ID));


COPY SRC_chicago_business_licenses
FROM '/tmp/chicago-business-licenses_2014-01-03.csv'
WITH DELIMITER ','
CSV HEADER;



--
-- create the DAT table for chicago_business_licenses and  
--  populate it with the first source file
-- 

DROP TABLE IF EXISTS DAT_chicago_business_licenses;

CREATE TABLE IF NOT EXISTS DAT_chicago_business_licenses(
chicago_business_licenses_row_id SERIAL,
start_date DATE,
end_date DATE DEFAULT NULL,
current_flag BOOLEAN DEFAULT true,
ID VARCHAR(20),
LICENSE_ID INTEGER,
ACCOUNT_NUMBER INTEGER,
SITE_NUMBER INTEGER,
LEGAL_NAME VARCHAR(150),
DOING_BUSINESS_AS_NAME VARCHAR(150),
ADDRESS VARCHAR(80),
CITY VARCHAR(30),
STATE CHAR(2),
ZIP_CODE CHAR(5),
WARD INTEGER,
PRECINCT INTEGER,
POLICE_DISTRICT INTEGER,
LICENSE_CODE INTEGER,
LICENSE_DESCRIPTION VARCHAR(100),
LICENSE_NUMBER INTEGER,
APPLICATION_TYPE VARCHAR(50),
PAYMENT_DATE DATE,
LICENSE_TERM_START_DATE DATE,
LICENSE_TERM_EXPIRATION_DATE DATE,
DATE_ISSUED DATE,
LICENSE_STATUS VARCHAR(10),
LICENSE_STATUS_CHANGE_DATE DATE,
LATITUDE FLOAT8,
LONGITUDE FLOAT8,
LOCATION POINT,
PRIMARY KEY(chicago_business_licenses_row_id),
UNIQUE(LICENSE_ID, start_date));

INSERT INTO DAT_chicago_business_licenses(
start_date,
ID,
LICENSE_ID,
ACCOUNT_NUMBER,
SITE_NUMBER,
LEGAL_NAME,
DOING_BUSINESS_AS_NAME,
ADDRESS,
CITY,
STATE,
ZIP_CODE,
WARD,
PRECINCT,
POLICE_DISTRICT,
LICENSE_CODE,
LICENSE_DESCRIPTION,
LICENSE_NUMBER,
APPLICATION_TYPE,
PAYMENT_DATE,
LICENSE_TERM_START_DATE,
LICENSE_TERM_EXPIRATION_DATE,
DATE_ISSUED,
LICENSE_STATUS,
LICENSE_STATUS_CHANGE_DATE,
LATITUDE,
LONGITUDE,
LOCATION)
SELECT
'2014-01-03' AS start_date,
ID,
LICENSE_ID,
ACCOUNT_NUMBER,
SITE_NUMBER,
LEGAL_NAME,
DOING_BUSINESS_AS_NAME,
ADDRESS,
CITY,
STATE,
ZIP_CODE,
WARD,
PRECINCT,
POLICE_DISTRICT,
LICENSE_CODE,
LICENSE_DESCRIPTION,
LICENSE_NUMBER, 
APPLICATION_TYPE,
PAYMENT_DATE,
LICENSE_TERM_START_DATE,
LICENSE_TERM_EXPIRATION_DATE,
DATE_ISSUED,
LICENSE_STATUS,
LICENSE_STATUS_CHANGE_DATE,
LATITUDE,
LONGITUDE,
LOCATION
FROM SRC_chicago_business_licenses;


--
-- insert new chicago-business-licenses tuples 
--  in DAT_master
--
INSERT INTO DAT_Master(
  start_date,
  end_date,
  current_flag,
  Location,
  LATITUDE, 
  LONGITUDE,
  obs_date,
  obs_ts,
  dataset_name,
  dataset_row_id,
  geom
)
SELECT
  start_date,
  end_date,
  current_flag,
  Location,
  LATITUDE, 
  LONGITUDE,
  LICENSE_TERM_START_DATE AS obs_date,
  NULL AS obs_ts,
  'chicago_business_licenses' AS dataset_name,
  chicago_business_licenses_row_id AS dataset_row_id,
  ST_SetSRID(ST_MakePoint(LONGITUDE, LATITUDE), 4326)
FROM
  DAT_chicago_business_licenses;
