CREATE TABLE IF NOT EXISTS src_weather (
    id SERIAL,
    wban VARCHAR(5) NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    station_type INTEGER,
    skycondition VARCHAR(50),
    skyconditionflag VARCHAR(15),
    visibility VARCHAR(15),
    visibilityflag VARCHAR(15),
    weathertype VARCHAR(15),
    weathertypeflag VARCHAR(15),
    drybulbfarenheit DOUBLE PRECISION NOT NULL,
    drybulbfarenheitflag VARCHAR(32),
    drybulbcelsius DOUBLE PRECISION,
    drybulbcelsiusflag VARCHAR(15),
    wetbulbfarenheit DOUBLE PRECISION,
    wetbulbfarenheitflag VARCHAR(32),
    wetbulbcelsius DOUBLE PRECISION,
    wetbulbcelsiusflag VARCHAR(32),
    dewpointfarenheit DOUBLE PRECISION,
    dewpointfarenheitflag VARCHAR(32),
    dewpointcelsius DOUBLE PRECISION,
    dewpointcelsiusflag VARCHAR(15),
    relativehumidity INTEGER,
    relativehumidityflag VARCHAR(32),
    windspeed INTEGER,
    windspeedflag VARCHAR(15),
    winddirection VARCHAR(15),
    winddirectionflag VARCHAR(32),
    valueforwindcharacter INTEGER,
    valueforwindcharacterflag VARCHAR(15),
    stationpressure DOUBLE PRECISION,
    stationpressureflag VARCHAR(32),
    pressuretendency INTEGER,
    pressuretendencyflag VARCHAR(32),
    pressurechange VARCHAR(15),
    pressurechangeflag VARCHAR(32),
    sealevelpressure DOUBLE PRECISION,
    sealevelpressureflag VARCHAR(15),
    recordtype VARCHAR(15),
    recordtypeflag VARCHAR(32),
    hourlyprecip DOUBLE PRECISION,
    hourlyprecipflag VARCHAR(15),
    altimeter DOUBLE PRECISION,
    altimeterflag VARCHAR(15),
    lon DOUBLE PRECISION,
    lat DOUBLE PRECISION,
    PRIMARY KEY id
);

SELECT AddGeometryColumn('public', 'src_weather', 'geom', 4326, 'POINT', 2);
CREATE INDEX date_time_idx on src_weather (date_time);
CREATE INDEX wban_idx on src_weather (wban);

