CREATE TABLE src_weather (
    wban VARCHAR(5) NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    station_type INTEGER NOT NULL,
    skycondition VARCHAR(23) NOT NULL,
    skyconditionflag VARCHAR(4),
    visibility VARCHAR(5) NOT NULL,
    visibilityflag VARCHAR(4),
    weathertype VARCHAR(13),
    weathertypeflag VARCHAR(4),
    drybulbfarenheit VARCHAR(3) NOT NULL,
    drybulbfarenheitflag VARCHAR(32),
    drybulbcelsius VARCHAR(5),
    drybulbcelsiusflag VARCHAR(4),
    wetbulbfarenheit VARCHAR(3) NOT NULL,
    wetbulbfarenheitflag VARCHAR(32),
    wetbulbcelsius VARCHAR(5),
    wetbulbcelsiusflag VARCHAR(32),
    dewpointfarenheit VARCHAR(4) NOT NULL,
    dewpointfarenheitflag VARCHAR(32),
    dewpointcelsius VARCHAR(5),
    dewpointcelsiusflag VARCHAR(4),
    relativehumidity VARCHAR(3) NOT NULL,
    relativehumidityflag VARCHAR(32),
    windspeed VARCHAR(4),
    windspeedflag VARCHAR(4),
    winddirection VARCHAR(4),
    winddirectionflag VARCHAR(32),
    valueforwindcharacter INTEGER,
    valueforwindcharacterflag VARCHAR(4),
    stationpressure VARCHAR(5) NOT NULL,
    stationpressureflag VARCHAR(32),
    pressuretendency INTEGER,
    pressuretendencyflag VARCHAR(32),
    pressurechange VARCHAR(4),
    pressurechangeflag VARCHAR(32),
    sealevelpressure VARCHAR(5) NOT NULL,
    sealevelpressureflag VARCHAR(4),
    recordtype VARCHAR(5) NOT NULL,
    recordtypeflag VARCHAR(32),
    hourlyprecip VARCHAR(5) NOT NULL,
    hourlyprecipflag VARCHAR(4),
    altimeter VARCHAR(5),
    altimeterflag VARCHAR(4)
);
